// Copyright 2025 Red Hat Inc.
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"fmt"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"runtime"
	"slices"
	"strings"
	"sync"
	"time"

	mmv1product "github.com/GoogleCloudPlatform/magic-modules/mmv1/api/product"
	"github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/plumbing"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
	"github.com/thekad/ansible-mmv1/pkg/ansible"
	"github.com/thekad/ansible-mmv1/pkg/api"
	tpl "github.com/thekad/ansible-mmv1/pkg/template"
)

const MMV1_REPO string = "https://github.com/GoogleCloudPlatform/magic-modules"
const MIN_VERSION string = "beta"

// generationWorkerCount caps concurrent module generation (templates + formatters).
func generationWorkerCount(numModules int) int {
	if numModules <= 1 {
		return 1
	}
	n := runtime.NumCPU()
	if n < 2 {
		n = 2
	}
	if n > 16 {
		n = 16
	}
	if n > numModules {
		n = numModules
	}
	return n
}

func generateModule(templateData *tpl.TemplateData, m *ansible.Module, noCode, noTests, noFormat bool) error {
	if !noCode {
		log.Info().Msgf("generating code for ansible module: %s", m)
		if err := templateData.GenerateCode(m); err != nil {
			return fmt.Errorf("generate code for %s: %w", m.Name, err)
		}
		if !noFormat {
			filePath := path.Join(templateData.ModuleDirectory, fmt.Sprintf("%s.py", m.Name))
			log.Info().Msgf("formatting ansible module file: %s", filePath)
			if err := formatFile(filePath, "black"); err != nil {
				return fmt.Errorf("format %s: %w", m.Name, err)
			}
		}
	}
	if !noTests || len(m.Resource.Mmv1.Examples) > 0 {
		log.Info().Msgf("generating tests for ansible module: %s", m)
		if err := templateData.GenerateTests(m); err != nil {
			return fmt.Errorf("generate tests for %s: %w", m.Name, err)
		}
		if !noFormat {
			dirPath := path.Join(templateData.IntegrationTestDirectory, m.Name)
			log.Info().Msgf("formatting integration tests for %s", m.Name)
			if err := formatFile(dirPath, "yamlfmt"); err != nil {
				return fmt.Errorf("format tests for %s: %w", m.Name, err)
			}
		}
	}
	return nil
}

func generateModules(templateData *tpl.TemplateData, modules []*ansible.Module, noCode, noTests, noFormat bool) error {
	if len(modules) == 0 {
		return nil
	}
	workers := generationWorkerCount(len(modules))
	jobs := make(chan *ansible.Module, len(modules))
	for _, m := range modules {
		jobs <- m
	}
	close(jobs)

	var wg sync.WaitGroup
	var mu sync.Mutex
	var firstErr error

	for w := 0; w < workers; w++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for m := range jobs {
				if err := generateModule(templateData, m, noCode, noTests, noFormat); err != nil {
					mu.Lock()
					if firstErr == nil {
						firstErr = err
					}
					mu.Unlock()
				}
			}
		}()
	}
	wg.Wait()
	return firstErr
}

// ProductConfig holds per-product configuration with optional resource list
type ProductConfig struct {
	Name      string   `mapstructure:"name"`
	Resources []string `mapstructure:"resources"`
}

// rootCmd represents the base command when called without any subcommands
var rootCmd = &cobra.Command{
	Use:   "ansible-mmv1",
	Short: "Generate Ansible modules from Magic Modules",
	Long: `ansible-mmv1 generates Ansible modules from Google's Magic Modules repository.
It reads product and resource definitions and generates Python modules and integration tests.`,
	PreRun: func(cmd *cobra.Command, args []string) {
		initLogging(cmd)
	},
}

func init() {
	cobra.OnInitialize(initConfig)

	// Set the run function here to avoid initialization cycle
	rootCmd.Run = runGenerate

	// Git flags
	rootCmd.Flags().String("git-url", MMV1_REPO, "git repository to clone")
	rootCmd.Flags().String("git-dir", "magic-modules", "path to clone magic modules repo")
	rootCmd.Flags().String("git-rev", "main", "git revision to checkout")
	rootCmd.Flags().Bool("git-pull", false, "git pull before checkout")
	rootCmd.Flags().Bool("no-git-clone", false, "skip git clone/checkout (use existing git directory)")
	rootCmd.Flags().Bool("no-git-pull", false, "negate --git-pull (useful to override config file)")

	// Path flags
	rootCmd.Flags().StringP("output", "o", "output", "path to write autogenerated files")
	rootCmd.Flags().StringP("overlay", "O", "overlay", "overlay directory (layout: products/, templates/) merged over the cloned mmv1 root")

	// Generation flags
	rootCmd.Flags().StringSlice("products", []string{}, "comma-separated list of products to generate")
	rootCmd.Flags().StringSlice("resources", []string{}, "comma-separated list of resources to generate")
	rootCmd.Flags().Bool("no-code", false, "skip code generation")
	rootCmd.Flags().Bool("no-tests", false, "skip test generation")
	rootCmd.Flags().Bool("no-format", false, "skip formatting files (i.e. black/yamlfmt)")
	rootCmd.Flags().Bool("overwrite", false, "overwrite existing files")
	rootCmd.Flags().String("min-version", MIN_VERSION, "minimum version to generate")

	// Logging flag
	rootCmd.Flags().StringP("log-level", "l", "info", "log level (trace, debug, info, warn, error, fatal)")

	// Config file flag
	rootCmd.Flags().StringP("config", "C", "", "path to config file")

	// Bind flags to viper (only for options that can come from config file)
	viper.BindPFlag("git.url", rootCmd.Flags().Lookup("git-url"))
	viper.BindPFlag("git.dir", rootCmd.Flags().Lookup("git-dir"))
	viper.BindPFlag("git.rev", rootCmd.Flags().Lookup("git-rev"))
	viper.BindPFlag("git.pull", rootCmd.Flags().Lookup("git-pull"))
	viper.BindPFlag("overlay", rootCmd.Flags().Lookup("overlay"))
	viper.BindPFlag("overwrite", rootCmd.Flags().Lookup("overwrite"))
	// Note: output, min-version, no-code, no-tests, no-format are flag-only (not in config file)
}

func initLogging(cmd *cobra.Command) {
	logLevelStr, _ := cmd.Flags().GetString("log-level")

	log.Logger = log.Output(zerolog.ConsoleWriter{
		Out:        os.Stderr,
		TimeFormat: time.RFC3339,
	})

	switch strings.ToLower(logLevelStr) {
	case "trace":
		zerolog.SetGlobalLevel(zerolog.TraceLevel)
	case "debug":
		zerolog.SetGlobalLevel(zerolog.DebugLevel)
	case "info":
		zerolog.SetGlobalLevel(zerolog.InfoLevel)
	case "warn":
		zerolog.SetGlobalLevel(zerolog.WarnLevel)
	case "error":
		zerolog.SetGlobalLevel(zerolog.ErrorLevel)
	case "fatal":
		zerolog.SetGlobalLevel(zerolog.FatalLevel)
	case "panic":
		zerolog.SetGlobalLevel(zerolog.FatalLevel)
	default:
		zerolog.SetGlobalLevel(zerolog.InfoLevel)
		log.Warn().Msgf("Unrecognized log level '%s', defaulting to 'info'", logLevelStr)
	}

	log.Debug().Msgf("Log level set to %s", zerolog.GlobalLevel())
}

func initConfig() {
	// Check for config file flag
	configFile, _ := rootCmd.Flags().GetString("config")
	if configFile != "" {
		viper.SetConfigFile(configFile)
	}

	// Read config file (if it exists)
	if err := viper.ReadInConfig(); err != nil {
		if _, ok := err.(viper.ConfigFileNotFoundError); !ok {
			// Config file was found but another error occurred
			log.Warn().Err(err).Msg("error reading config file")
		}
	} else {
		log.Info().Msgf("using config file: %s", viper.ConfigFileUsed())
	}
}

// buildProductResourceMap builds a map of product names to their resource lists
func buildProductResourceMap(products []ProductConfig) map[string][]string {
	prm := make(map[string][]string)
	for _, p := range products {
		// Normalize resource names to lowercase
		resources := make([]string, len(p.Resources))
		for i, r := range p.Resources {
			resources[i] = strings.ToLower(strings.TrimSpace(r))
		}
		prm[strings.ToLower(p.Name)] = resources
	}
	return prm
}

// getProductNames extracts product names from config
func getProductNames(products []ProductConfig) []string {
	names := make([]string, len(products))
	for i, p := range products {
		names[i] = strings.ToLower(p.Name)
	}
	return names
}

// getProductsConfig returns the products configuration, handling both
// config file format (products with nested resources) and CLI format (flat lists)
func getProductsConfig(cmd *cobra.Command) []ProductConfig {
	// First check if products are defined in config file format
	var configProducts []ProductConfig
	if err := viper.UnmarshalKey("products", &configProducts); err == nil && len(configProducts) > 0 {
		return configProducts
	}

	// Fall back to CLI-style flat lists
	productNames, _ := cmd.Flags().GetStringSlice("products")
	resourceNames, _ := cmd.Flags().GetStringSlice("resources")

	// Normalize to lowercase
	for i, p := range productNames {
		productNames[i] = strings.ToLower(strings.TrimSpace(p))
	}
	resources := make([]string, len(resourceNames))
	for i, r := range resourceNames {
		resources[i] = strings.ToLower(strings.TrimSpace(r))
	}

	// Build ProductConfig list from CLI args
	products := make([]ProductConfig, len(productNames))
	for i, p := range productNames {
		products[i] = ProductConfig{
			Name:      p,
			Resources: resources, // all products share the same resource filter
		}
	}
	return products
}

// doGitClone clones the git repository to the given path
func doGitClone(path string, ref string, pull bool, url string) error {
	log.Info().Msgf("git-clone %s to %s\n", url, path)
	_, err := git.PlainClone(path, false, &git.CloneOptions{
		URL:      url,
		Progress: os.Stdout,
	})
	if err != nil {
		log.Warn().Msgf("git-clone: %s", err)
	}

	repo, err := git.PlainOpen(path)
	if err != nil {
		return fmt.Errorf("can't open git dir %s: %v", path, err)
	}

	worktree, err := repo.Worktree()
	if err != nil {
		return fmt.Errorf("can't open worktree: %v", err)
	}

	if pull {
		if err := worktree.Pull(&git.PullOptions{RemoteName: "origin"}); err != nil {
			log.Warn().Msgf("can't pull from 'origin' remote: %v", err)
		} else {
			log.Info().Msg("git-pull: success")
		}
	}

	h, err := repo.ResolveRevision(plumbing.Revision(ref))
	if err != nil {
		return fmt.Errorf("can't resolve revision %s: :%v", ref, err)
	}

	coOpts := git.CheckoutOptions{
		Hash:  *h,
		Force: true,
	}
	if err := worktree.Checkout(&coOpts); err != nil {
		return fmt.Errorf("can't checkout worktree: %v", err)
	}

	log.Info().Msgf("git-checkout %s: success", ref)

	return nil
}

func runGenerate(cmd *cobra.Command, args []string) {
	// Get configuration values from viper (config file + flags merged)
	gitURL := viper.GetString("git.url")
	gitDir := viper.GetString("git.dir")
	gitRev := viper.GetString("git.rev")
	gitPull := viper.GetBool("git.pull")
	overlayPath := viper.GetString("overlay")
	overwrite := viper.GetBool("overwrite")

	// Get flag-only values (not available in config file)
	output, _ := cmd.Flags().GetString("output")
	noCode, _ := cmd.Flags().GetBool("no-code")
	noTests, _ := cmd.Flags().GetBool("no-tests")
	noFormat, _ := cmd.Flags().GetBool("no-format")
	minVersion, _ := cmd.Flags().GetString("min-version")
	noGitClone, _ := cmd.Flags().GetBool("no-git-clone")
	noGitPull, _ := cmd.Flags().GetBool("no-git-pull")

	// Apply --no-git-pull to negate --git-pull (or config file setting)
	if noGitPull {
		gitPull = false
	}

	// Get products configuration
	productsConfig := getProductsConfig(cmd)
	productResources := buildProductResourceMap(productsConfig)
	productNames := getProductNames(productsConfig)

	absGitDir, _ := filepath.Abs(gitDir)
	var overlayDir string
	if overlayPath != "" {
		var err error
		overlayDir, err = filepath.Abs(overlayPath)
		if err != nil {
			log.Fatal().Err(err).Msg("invalid overlay path")
		}
	}

	ansibleTemplateDir, err := filepath.Abs("templates") // ansible specific templates
	if err != nil {
		log.Fatal().Err(err).Msg("invalid ansible templates path")
	}

	if noGitClone {
		log.Info().Msg("skipping git clone/checkout (--no-git-clone)")
	} else {
		if err := doGitClone(absGitDir, gitRev, gitPull, gitURL); err != nil {
			log.Fatal().Err(err).Msg("failed to clone git repository")
		}
	}

	mmv1Root := filepath.Join(absGitDir, "mmv1")
	log.Info().Msgf("mmv1 base directory: %s", mmv1Root)
	if overlayDir == "" {
		log.Info().Msg("overlay directory: (none)")
	} else {
		log.Info().Msgf("overlay directory: %s", overlayDir)
	}

	sysfs, loader, err := api.LoadProducts(mmv1Root, overlayDir, minVersion, productNames)
	if err != nil {
		log.Fatal().Err(err).Msg("failed to load Magic Modules (loader)")
	}

	log.Info().Msgf("ansible specific templates: %s", ansibleTemplateDir)
	templateData := tpl.NewTemplateData(ansibleTemplateDir, output, overwrite)
	log.Debug().Msgf("template data: %v", templateData)

	modulesToGenerate := []*ansible.Module{}
	minVersionObj := &mmv1product.Version{Name: minVersion}

	for _, pKey := range api.ProductKeys(loader) {
		short := api.ShortName(pKey)
		if len(productNames) > 0 && !slices.Contains(productNames, short) {
			continue
		}

		mmv1Product := loader.Products[pKey]
		apiProd := api.WrapProduct(mmv1Product, mmv1Root)
		resourceList := productResources[short]
		log.Debug().Msgf("resource list for %s: %v", short, resourceList)

		for _, mmRes := range mmv1Product.Objects {
			if mmRes == nil {
				continue
			}
			/*
				if len(resourceList) > 0 && !slices.Contains(resourceList, strings.ToLower(mmRes.Name)) {
					continue
				}
			*/

			if err := api.ReloadAnsibleExamples(mmRes, sysfs); err != nil {
				log.Fatal().Err(err).Str("product", short).Str("resource", mmRes.Name).Msg("failed to load Ansible example templates")
			}

			r := api.WrapResource(mmRes, apiProd, mmv1Root)
			if r.Mmv1.NotInVersion(minVersionObj) {
				log.Warn().Msgf("resource %s.%s minimum version is %v, but %s is required", r.Parent.Name, r.Name, r.MinVersion(), minVersion)
				continue
			}

			module := ansible.NewFromResource(r)
			module.MinVersion = r.MinVersion()
			modulesToGenerate = append(modulesToGenerate, module)
		}
	}
	if err := generateModules(templateData, modulesToGenerate, noCode, noTests, noFormat); err != nil {
		log.Fatal().Err(err).Msg("module generation failed")
	}
}

func formatFile(filePath string, formatType string) error {
	log.Debug().Msgf("running %s on file: %s", formatType, filePath)
	switch formatType {
	case "black":
		if blackCmd := which("black"); blackCmd == "" {
			return fmt.Errorf("black not found in PATH")
		} else {
			return runCommand(fmt.Sprintf("%s --quiet %s", blackCmd, filePath), filepath.Dir(filePath))
		}
	case "yamlfmt":
		if yamlFmtCmd := which("yamlfmt"); yamlFmtCmd == "" {
			return fmt.Errorf("yamlfmt not found in PATH")
		} else {
			return runCommand(fmt.Sprintf("yamlfmt %s", filePath), filePath)
		}
	}
	return nil
}

// which searches for the given executable and returns the full path to it
// Returns empty string if the command is not found
func which(name string) string {
	if path, err := exec.LookPath(name); err == nil {
		return path
	}

	return ""
}

func runCommand(command string, dir string) error {
	parts := strings.Split(command, " ")
	cmd := exec.Command(parts[0], parts[1:]...)

	// Set working directory if provided
	if dir != "" {
		log.Debug().Msgf("changing directory to: %s", dir)
		cmd.Dir = dir
	}

	log.Debug().Msgf("running command: %s", command)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	return cmd.Run()
}

func main() {
	if err := rootCmd.Execute(); err != nil {
		log.Fatal().Err(err).Msg("command failed")
	}
}
