---
custom_code:
  pre_read: |
    # if set from a registered variable, get the resource basename
    resource.url_params["trigger_id"] = module.params["name"].split("/")[-1]

  pre_create: _drop

  pre_delete: |
    # set the trigger ID from the existing object's ID before delete
    if existing_obj.get("id"):
      module.url_params["trigger_id"] = existing_obj["id"]
    else:
      module.url_params["trigger_id"] = existing_obj["name"].split("/")[-1]

  pre_update: |
    # set the trigger ID from the existing object's ID before update
    if existing_obj.get("id"):
      module.url_params["trigger_id"] = existing_obj["id"]
    else:
      module.url_params["trigger_id"] = existing_obj["name"].split("/")[-1]